services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: wget --spider http://127.0.0.1:5173/
      interval: 5s

    stop_signal: SIGTERM
    init: true # Kill children process

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    healthcheck:
      test: nc -z 127.0.0.1 3000
      interval: 5s
      start_period: 30s

    stop_signal: SIGTERM
    init: true # Kill children process
  nginx:
    build:
      context: ./apps/nginx
    ports:
      - 8080:8080
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
